Update nxaddsite

diff --git a/bin/nxaddsite b/bin/nxaddsite
--- a/bin/nxaddsite
+++ b/bin/nxaddsite
@@ -11,6 +11,7 @@ _usage() {
   cat <<- EOF
 
 Description: Site Creation Tool For Nexcess Cloud Servers.
+Requires: Nocworx api-token
 Usage: nxaddsite -d
 
    Supported Options:
@@ -32,36 +33,48 @@ _normalize_domain(){
 
 }
 
-#create_site(){
+
+create_site(){
+
+  domain="$1"
+  printf "%sCreating ${domain}\n"
+  sleep 3
+#  app_id=$(echo "${siteworx}" | grep 'app_id' | awk '{print $2}');
+#  service_id=$(echo "${siteworx}" | grep 'service_id' | awk '{print $2}');
 
 ## Todo
+# Remove the elements for headers array we don't want from existing array in check_api
+# should remove -w "%{http_code}" and -o "/dev/null"
+#  headers=("${headers[@]:0:2}")
 
-# While true loop to check the task uri status
-  while true; do
-    site_status=$(curl -s "${api_url}/${acc_id}${task_uri}" "${headers[@]}" | jq -r '.status')
+# Add new headers to the existing array specifically for the POST request
+#  headers+=(
+#    -H "Content-type: application/json"
+#    -d "{\"service_id\":\"${service_id}\", \"install_app\": \"on\", \"nickname\": \"${domain}\"}"
+#  )
+# Set site create endpoint
+#  site_create_endpoint="${acc_id}/v1/cloud-account/"
 
-    if [[ "${site_status}" == "processing" ]]; then
-      sleep 5
-    elif [[ "${site_status}" == "success" ]]; then
-      printf "done\n"
-      printf "%s ${domain} created successfully\n"
-      break
-    elif [[ "${site_status}" == "failure" ]]; then
-      printf "done\n"
-      printf "site creation failed\n"
-      break
-    fi
-  done
+# make the curl request to create site
+#  site_create_curl=$(curl -sX POST "${api_url}/${site_create_endpoint}" "${headers[@]}")
 
+# Kick off the site creation and grab the task uri
+#  task_uri=$(echo "${site_create_curl}" | jq -r '.metadata.uri')
 
-#}
+# remove the -d header from the array
+#  headers=("${headers[@]:0:2}")
 
-#_get_site_info(){
+}
 
-## Todo
-## Determine what type of plan, create the header for the request, send to create site
+# Function to process domains from a file
+process_domains() {
 
-#}
+    # Read each domain from the file, normalize domain and create site
+    while IFS= read -r domain; do
+        normalized_domain=$(_normalize_domain "${domain}")
+       create_site "$normalized_domain"
+    done < "$file"
+}
 
 check_api(){
 
@@ -97,34 +110,80 @@ check_api(){
   if [[ "${resp}" -ne 200 ]]; then
      printf "done\n"
      printf "%sAPI Token  not valid ${resp}\n";
+     exit 1
   else
      printf "done\n"
-#     _get_site_info;
   fi
 
 }
 
-_check_api_input(){
+# validate input on hostname, file path
+validate_input(){
 
-# prompt for api-key if -a flag is used
-  if [[ -z "${NWTOKEN}" && "${API_KEY}" == "YES" ]]; then
-      read -r -p "Enter API-TOKEN: " api_token
-      NWTOKEN="${api_token}"
+  local input pattern
+
+  input="$1"
+  pattern="$2"
+
+  if [[ ! "${input}" =~ ${pattern} ]]; then
+      printf "Error: Invalid input. Please try again\n"
+      return 1
   fi
-    check_api;
+  return 0
 
 }
 
 _check_user_input(){
 
-  if [[ "${DOMAIN}" == "YES" ]]; then
-     read -r -p "Domain: " domain
-       domain="$(_normalize_domain ${domain})"
-  elif [[ "${FILE}" == "YES" ]]; then
-     read -r -p "Full path to txt file: " TXT
-  else
-      printf "Please select an option\n"
-  fi
+  host_pattern="^[^.|*].*$"
+  path_pattern="^[^*]+$"
+
+  case "${FILE}-${DOMAIN}" in
+      YES-YES)
+          printf "You Can Only Select One Option, See Help Section.\n"
+          exit 1
+          ;;
+      *)
+          ;;
+  esac
+
+  case "${DOMAIN}" in
+        YES)
+            while true; do
+                read -r -p "Domain: " domain
+                if ! validate_input "${domain}" "${host_pattern}"; then
+                    continue
+                fi
+                domain="$(_normalize_domain "${domain}")"
+                check_api
+                create_site "${domain}"
+                break
+            done
+            ;;
+        *)
+            ;;
+    esac
+
+    case "${FILE}" in
+        YES)
+            while true; do
+                read -r -p "Path To Domain.txt File: " file
+                if ! validate_input "${file}" "${path_pattern}"; then
+                    continue
+                fi
+                if [ ! -s "${file}" ]; then
+                    printf "%sFile ${file} Does Not Exist Or Is Empty.\n"
+                    exit 1
+                fi
+                check_api
+                process_domains
+                break
+            done
+            ;;
+        *)
+            ;;
+    esac
+
 }
 
 _cmdline() {
@@ -194,13 +253,12 @@ main(){
     exit 1
   fi
 
-#
+  if [[ -z "${NWTOKEN}" ]]; then
+      read -r -p "Enter API-TOKEN: " api_token
+      NWTOKEN="${api_token}"
+  fi
+
   _check_user_input
-
-
-# check for input or an existing api key
-
-  _check_api_input
 
 }
 
