Update nxaddsite

diff --git a/bin/nxaddsite b/bin/nxaddsite
--- a/bin/nxaddsite
+++ b/bin/nxaddsite
@@ -10,17 +10,18 @@ _usage() {
 # Print help
   cat <<- EOF
 
-Description: Site Creation Tool For Nexcess Cloud Servers.
+Description: Site Creation Tool For MWP and Magento.
 Requires: Nocworx api-token
-Usage: nxaddsite -d
+Usage: nxaddsite -d domain.com; nxaddsite -f file.txt
 
    Supported Options:
 
-     -d|--domain   Add Domain
-     -f|--file     TXT File With List Of Domains
+     -d|--domain   Create a site
+     -f|--file     Create muliple domains from a file.
      -h|--help     Display This Message
 
 EOF
+
 }
 
 _normalize_domain(){
@@ -28,6 +29,7 @@ _normalize_domain(){
   local sed_args
 
   sed_args=(-e 's/https?:\/\///' -e 's/\/.*//' -e 's,\.$,,')
+
 # Strip URL of any extra slashes
   echo "$1" | sed -r "${sed_args[@]}" | tr '[:upper:]' '[:lower:]'
 
@@ -35,69 +37,105 @@ _normalize_domain(){
 
 _delete_api_token(){
 
-  printf "Deleting client api-token..."
-
-# Reset Headers
-  headers=("${headers[@]:0:0}")
-
-# Add new header
-  headers=(
-    -H "Authorization: Bearer ${NWTOKEN}"
-    -H "Content-type: application/json"
-    -H "Accept: application/json"
-   )
+  printf "deleting client api-token..."
 
 # delete token api request
-   curl -sX DELETE "${api_url}${token_endpoint}/${client_token_id}" "${headers[@]}"
-   printf "done\n"
+
+  if ! curl -sX DELETE "${api_url}${token_endpoint}/${client_token_id}" "${headers[@]}" >/dev/null 2>&1; then
+      printf "done\n"
+      printf "Failed to delete TokenID: %s\n" "${client_token_id}"
+  else
+      printf "done\n"
+  fi
+
+}
+
+scan_site(){
+
+  local end found new_site_data new_site_list new_site_count new_domain
+# Reset Headers to exclude -d
+  headers=("${headers[@]:0:6}")
+
+  end=$((SECONDS+5))
+  found=false
+
+# Kind of janky workaround to get the new domain. This api endpoint does not give a task uri so we are left
+# With a best guess. We are going to grab the list of sites and count them, if the number is greater than our inital list show the last one which should be the newly added domain
+
+ while [ ${SECONDS} -lt ${end} ]; do
+
+     new_site_data=$(curl -s "${api_url}${service_data_endpoint}" "${headers[@]}");
+     if [[ "${app_id}" == "11" ]]; then
+        new_site_list=$(echo "${new_site_data}" | jq -r '.sites[].identity, .child_sites[].identity');
+     else
+        new_site_list=$(echo "${new_site_data}" | jq -r '.sites[].identity');
+     fi
+     new_site_count=$(echo "${new_site_list}" | wc -l);
+     if [[ "${new_site_count}" -gt "${site_count}" ]]; then
+         new_domain=$(echo "${new_site_list}" | tail -n1);
+          printf "%s: %s\n" "${domain}" "${new_domain}"
+         found=true
+         break
+     fi
+     sleep 1  # Sleep for 1 second before trying again
+ done
+
+# If no new domain found after the loop
+  if [ "${found}" = false ]; then
+      printf "unable to find new domain\n"
+  fi
+
 }
 
 _create_site(){
 
+  local legacy_api_url legacy_endpoint client_headers
   domain="$1"
+
 # set legacy endpoints
   legacy_api_url='https://portal.nexcess.net/'
   legacy_endpoint='cloud-account'
 
-# Extract app_id from siteworx data
-  app_id=$(echo "${siteworx}" | grep 'app_id' | awk '{print $2}');
-
-# Reset Headers
-  headers=("${headers[@]:0:0}")
-
 # create new header because we need clients api token for this call.
-
-  headers=(
+  client_headers=(
     -H "Authorization: Bearer ${client_token_value}"
+    -H "Content-Type: application/json"
     -H "Accept: application/json"
-    -H "Accept: application/json"
-    -d "{\"service_id\": \"${service_id}\", \"install_app\": \"on\",\"nickname\": \"${domain}\"}"
  )
-  printf "%sCreating ${domain}\n"
-###todo
 
+  if [[ "${app_id}" == "11" ]]; then
+    legacy_endpoint="cloud-account/${site_id}"
+    client_headers+=(
+         -d "{\"nickname\": \"${domain}\", \"app_id\": \"${app_id}\", \"install_app\": \"off\", \"_action\": \"add-child-account\"}")
+  else
+    legacy_endpoint='cloud-account'
+    client_headers+=(
+         -d "{\"service_id\": \"${service_id}\", \"install_app\": \"on\",\"nickname\": \"${domain}\"}")
+  fi
 
-# Create site with POST request to legacy api
-  curl-L -X POST "${legacy_api_url}${legacy_endpoint}" "${header[@]}"
-
-# sleep for 5 seconds to give api time.
-  sleep 5
+  if ! curl -sLX POST "${legacy_api_url}${legacy_endpoint}" "${client_headers[@]}" >/dev/null 2>&1; then
+      printf "Failed to create %s" "${domain}\n"
+  else
+      scan_site
+  fi
 
 }
 
-# Function to process domains from a file
 _process_domains() {
 
-    # Read each domain from the file, normalize domain and create site
-    while IFS= read -r domain; do
-        normalized_domain=$(_normalize_domain "${domain}")
-       _create_site "$normalized_domain"
-    done < "$file"
+# Read each domain from the file, normalize domain and create site
+  printf "processing domains from %s\n" "${file}"
+  while IFS= read -r domain; do
+      normalized_domain=$(_normalize_domain "${domain}")
+      _create_site "${normalized_domain}"
+      sleep 5
+  done < "${file}"
+
 }
 
 _create_api_token(){
 
-  printf "Creating client api-token..."
+  printf "creating client api-token..."
 # Set Token Endpoint
   token_endpoint="${acc_id}/v1/api-token"
 
@@ -107,73 +145,45 @@ _create_api_token(){
     -d "{\"name\":\"nxaddsite-token\"}"
      )
 
-# Create Cleint api token and save it as a var
-  token_resp=$(curl -sX POST "${api_url}${token_endpoint}" "${headers[@]}");
-
-# Extract Token ID and Value from token_resp
-  client_token_id=$(echo "${token_resp}" | jq -r '.id');
-  client_token_value=$(echo "${token_resp}" | jq -r '.token');
-  printf "done\n"
-
-  case "${DOMAIN}" in
-      "YES")
-          _create_site "${domain}"
-          ;;
-      *)
-          _process_domains
-          ;;
-  esac
-}
-
-
-_site_info(){
-
-  printf "Checking Site Info..."
-# Extract app_id from siteworx data
-  app_id=$(echo "${siteworx}" | grep 'app_id' | awk '{print $2}');
-
-# Check app_id to confirm we are working with wordpress or woo-commerce
-  case ${app_id} in
-      17 | 19)
-          printf "done\n"
-          ;;
-      *)
-          printf "done\n"
-          printf "Functionality is designed only for WordPress/Woo and Magento environments.\n"
-          exit 1
-          ;;
-  esac
+# Check if the curl command succeeded
+  if ! token_resp=$(curl -sX POST "${api_url}${token_endpoint}" "${headers[@]}"); then
+      printf "done\n"
+      printf "failed to create client api-token"
+      exit 1
+  else
+     # Extract Token ID and Value from token_resp
+     client_token_id=$(echo "${token_resp}" | jq -r '.id');
+     client_token_value=$(echo "${token_resp}" | jq -r '.token');
+     printf "done\n"
+  fi
 
 }
 
 _site_count(){
 
-# Remove the elements for headers array we don't want from existing array in check_api
-# should remove -w "%{http_code}" and -o "/dev/null"
+  local  site_total extra_domain total_sites
 
-  headers=("${headers[@]:0:2}")
-# add new elements to header array
-  headers=+(
-    -H "Accept: application/json"
-  )
+  printf "checking plan capacity..."
 
-  printf "Site Check..."
+# Check app_id to confirm we are working with wordpress or woo-commerce
+  case ${app_id} in
+      17 | 19)
+          initial_site_list=$(echo "${service_data}" | jq -r '.sites[].identity');
+          site_total=$(echo "${package_data}" | jq -r '.primary_accounts');
+          ;;
+      11)
+          initial_site_list=$(echo "${service_data}" | jq -r '.sites[].identity, .child_sites[].identity');
+          site_total=$(echo "${package_data}" | jq -r '.child_accounts');
+          site_total=$((site_total + 1));
+          ;;
+      *)
+          printf "done\n"
+          printf "functionality is designed only for WordPress/Woo and Magento environments.\n"
+          exit 1
+          ;;
+  esac
 
-# Extract service_id and package_id from Siteworx data
-  service_id=$(echo "${siteworx}" | grep 'service_id' | awk '{print $2}');
-  package_id=$(echo "${siteworx}" | grep 'package_id' | awk '{print $2}');
-
-# Set Endpoints
-  site_count_endpoint="${acc_id}/v1/service/site/${service_id}"
-  site_total_endpoint="${acc_id}/v1/package/site/${package_id}"
-
-# Fetch site data from API
-  site_count=$(curl -s "${api_url}${site_count_endpoint}" "${headers[@]}" | jq -r '.sites[].identity' | wc -l);
-  site_total=$(curl -s "${api_url}${site_total_endpoint}" "${headers[@]}" | jq -r '.primary_accounts');
-  printf "done\n"
-
-# Print site usage information
-  printf "%sSites Used (${site_count}/${site_total})\n"
+  site_count=$(echo "${initial_site_list}" | wc -l);
 
 # Determine extra domains/sites
   if [[ "${DOMAIN}" == "YES" ]]; then
@@ -187,22 +197,51 @@ _site_count(){
 
 # Check if plan can accommodate additional sites
   if [[ "${total_sites}" -gt "${site_total}" ]]; then
-     printf "%sThis plan can only fit ${site_total} site(s), please upgrade to fit ${total_sites}\n"
+     printf "done\n"
+     printf "site limit reached, please upgrade to fit %s\n" "${total_sites}"
      exit 1
   fi
+  printf "done %d/%d\n" "${site_count}" "${site_total}"
 
+}
+
+_get_site_info(){
+  local plan_name
+  printf "Getting site info..."
+
+# remove -w "%{http_code}" and -o "/dev/null"
+  headers=("${headers[@]:0:2}")
+
+# add new element to header array
+  headers+=(
+    -H "Accept: application/json"
+  )
+
+# Extract service_id and package_id from Siteworx data
+  service_id=$(echo "${siteworx}" | grep 'service_id' | awk '{print $2}');
+  package_id=$(echo "${siteworx}" | grep 'package_id' | awk '{print $2}');
+  app_id=$(echo "${siteworx}" | grep 'app_id' | awk '{print $2}');
+  site_id=$(echo "${siteworx}" | grep 'account_id' | awk '{print $2}');
+
+# Set service and package endpoints
+  service_data_endpoint="${acc_id}/v1/service/site/${service_id}"
+  package_data_endpoint="${acc_id}/v1/package/site/${package_id}"
+# Save data
+  service_data=$(curl -s "${api_url}${service_data_endpoint}" "${headers[@]}");
+  package_data=$(curl -s "${api_url}${package_data_endpoint}" "${headers[@]}");
+  plan_name=$(echo "${service_data}" | jq -r '.identity');
+  printf "done\n"
+
+  printf "AccountID: %s\n" "${acc_id}"
+  printf "Plan Name: %s\n" "${plan_name}"
+  printf "ServiceID: %s\n" "${service_id}"
 }
 
 _check_api(){
 
-# Declare local variables
   local resp
 
-# Define siteworx var
-  siteworx=$(sudo -u iworx /usr/local/interworx/bin/config.pex --list --siteworx "${dom}");
-
 # Extract site ID and account ID from siteworx data
-  site_id=$(echo "${siteworx}" | grep 'account_id' | awk '{print $2}');
   acc_id=$(echo "${siteworx}" | grep '^client_id' | awk '{print $2}');
 
 # Set headers for the API request
@@ -212,12 +251,12 @@ _check_api(){
     -w "%{http_code}"
     -o "/dev/null"
   )
-# I want to hit a less impactful endpoint to test the api token
+# Goal: hit a less impactful endpoint to test the api token
 # Set API URL and client endpoint
   api_url='https://nocworx.nexcess.net/api/v1/as-client/'
   client_endpoint="${acc_id}/v1/client"
 
-  printf "\nChecking api-key..."
+  printf "authenticating NWTOKEN..."
 
 # Send curl to check api response
   resp=$(curl --silent "${api_url}${client_endpoint}" "${headers[@]}");
@@ -226,105 +265,12 @@ _check_api(){
 # Else try to get the container info with api info
   if [[ "${resp}" -ne 200 ]]; then
      printf "done\n"
-     printf "%sAPI Token  not valid ${resp}\n";
+     printf "authentication Failed %s\n" "${resp}";
      exit 1
   else
      printf "done\n"
   fi
 
-}
-
-# Description: Validates input against a specified pattern.
-# Parameters:
-# input: The input string to be validated.
-# pattern: The regular expression pattern used for validation.
-# Returns:
-# 0 if the input matches the pattern (valid input).
-# 1 if the input does not match the pattern (invalid input).
-
-_validate_input(){
-
-# Declare local variables for input and pattern
-  local input pattern
-
-# Assign input and pattern from function parameters
-  input="$1"
-  pattern="$2"
-
-# Check if input matches the pattern using regular expression
-  if [[ ! "${input}" =~ ${pattern} ]]; then
-      # Print error message if input does not match the pattern
-      printf "Error: Invalid input. Please try again\n"
-      # Return 1 to indicate invalid input
-      return 1
-  fi
-# Return 0 to indicate valid input
-  return 0
-
-}
-
-# Description: Validates user input for domain and file paths.
-_check_user_input(){
-
-# Define regular expression patterns for domain and file paths
-  host_pattern="^[^.|*].*$"
-  path_pattern="^[^*]+$"
-
-# Check for mutually exclusive options and handle accordingly
-  case "${FILE}-${DOMAIN}" in
-      YES-YES)
-          # Print error message if both FILE and DOMAIN are set to YES
-          printf "You Can Only Select One Option, See Help Section.\n"
-          # Exit with error status 1
-          exit 1
-          ;;
-      *)
-          # No conflict between options, continue processing
-          ;;
-  esac
-# Validate domain input if DOMAIN is set to YES
-  case "${DOMAIN}" in
-        YES)
-            while true; do
-                # Prompt user for domain input
-                read -r -p "Domain: " domain
-                # Validate domain input against host pattern
-                if ! _validate_input "${domain}" "${host_pattern}"; then
-                    continue # Continue loop if input is invalid
-                fi
-                # Normalize domain input (if needed)
-                domain="$(_normalize_domain "${domain}")"
-                break # Break out of loop if input is valid
-            done
-            ;;
-        *)
-            # DOMAIN is not set to YES, skip domain validation
-            ;;
-    esac
-
-# Validate file path input if FILE is set to YES
-    case "${FILE}" in
-        YES)
-            while true; do
-                # Prompt user for file path input
-                read -r -p "Path To Domain.txt File: " file
-                # Validate file path input against path pattern
-                if ! _validate_input "${file}" "${path_pattern}"; then
-                    continue # Continue loop if input is invalid
-                fi
-                # Check if file exists and is not empty
-                if [ ! -s "${file}" ]; then
-                    printf "%sFile ${file} Does Not Exist Or Is Empty.\n"
-                    # Exit with error status 1 if file is missing or empty
-                    exit 1
-                fi
-                break # Break out of loop if input is valid
-            done
-            ;;
-        *)
-            # FILE is not set to YES, skip file path validation
-            ;;
-    esac
 }
 
 _cmdline() {
@@ -353,7 +299,6 @@ _cmdline() {
   done
 
   echo "$args";
-
 }
 
 main(){
@@ -362,14 +307,20 @@ main(){
 
   mapfile -t cmdline < <(_cmdline | tr ' ' '\n');
 
-  while getopts ":dfh" OPTION "${cmdline[@]}"; do
+  while getopts ":d:f:h" OPTION "${cmdline[@]}"; do
 
     case $OPTION in
       d)
-        DOMAIN="YES";
+        DOMAIN="YES"
+        domain=$(_normalize_domain "${OPTARG}")
         ;;
       f)
-        FILE="YES";
+        FILE="YES"
+        file="${OPTARG}"
+          if [ ! -s "${file}" ]; then
+            printf "%s Does Not Exist Or Is Empty.\n" "${file}"
+            exit 1
+        fi;
         ;;
       h)
         _usage;
@@ -382,11 +333,27 @@ main(){
     esac
   done
 
-# Set variables for the domain information
+  case "${DOMAIN}${FILE}" in
+    "YESYES")
+        printf "Only one option can be selected.\n"
+        exit 1
+        ;;
+    *)
+        ;;
+  esac
 
+  if [[ ! $(hostname) =~ cloudhost ]]; then
+      printf "nxaddsite is only available on Nexcess Cloud Servers\n";
+      exit 1;
+  fi
+
+# Set variables for the domain information
   user="$(pwd | grep -Po "/(chroot/)?home/\K[^/]*")";
   dom="$(pwd| grep -Po "/(chroot/)?home/${user}/\K[^/]*")";
   vhost=$(find /etc/httpd/conf.d/ -type f -iname "vhost_${dom}.conf")
+
+# Define siteworx var
+  siteworx=$(sudo -u iworx /usr/local/interworx/bin/config.pex --list --siteworx "${dom}");
 
 # Make sure we are in a domain directory.
   case "${vhost}" in
@@ -408,21 +375,29 @@ main(){
           ;;
   esac
 
-
-# Verify Input
-  _check_user_input
-
 # Verify admin api token works
   _check_api
+# check plan for site details
+ _get_site_info
 
 # Determine if sites can fit on existing plan
   _site_count
 
-# Determine app id
-  _site_info
-
 # Create customer api token
-#  _create_api_token
+  _create_api_token
+
+  case "${DOMAIN}" in
+      "YES")
+          printf "creating %s\n" "${domain}"
+          _create_site "${domain}"
+          ;;
+      *)
+          _process_domains
+          ;;
+  esac
+
+# Delete customer created api token
+  _delete_api_token
 
 }
 
